# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k8TC6HmiCMz2WYk2w_aIti_FU79Dd2_a
"""

import streamlit as st
import streamlit.components.v1 as components

st.set_page_config(
    page_title="Manish's Aesthetic Edits",
    page_icon="🎬",
    layout="centered",
    initial_sidebar_state="auto",
)

# Custom CSS for aesthetics
st.markdown("""
    <style>
    body {
        background-color: #FFF9E5;
        color: #333333;
        font-family: 'Helvetica Neue', sans-serif;
    }
    .title {
        font-size: 2.5em;
        font-weight: 600;
        text-align: center;
        margin-bottom: 0.5em;
        color: #A67B00;
    }
    .subtitle {
        font-size: 1.2em;
        text-align: center;
        margin-bottom: 2em;
        color: #666666;
    }
    .video-box {
        background: #FFF3C7;
        padding: 1em;
        border-radius: 15px;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
        margin-bottom: 2em;
    }
    </style>
""", unsafe_allow_html=True)

# Title and subtitle
st.markdown('<div class="title">🎞️ Manish's Aesthetic Edits</div>', unsafe_allow_html=True)
st.markdown('<div class="subtitle">Soft, minimal edits of your favorite films and music</div>', unsafe_allow_html=True)

# Video links - You can replace these with your actual YouTube video links
video_links = [
    "https://www.youtube.com/embed/dQw4w9WgXcQ",  # Example placeholder
    "https://www.youtube.com/embed/3JZ_D3ELwOQ",
    "https://www.youtube.com/embed/tgbNymZ7vqY"
]

# Display each video in a styled box
for link in video_links:
    st.markdown('<div class="video-box">', unsafe_allow_html=True)
    components.iframe(link, height=315)
    st.markdown('</div>', unsafe_allow_html=True)

# Footer
st.markdown("""
    <hr>
    <div style='text-align:center; font-size: 0.9em; color: #999;'>
        © 2025 Manish Shriram | Aesthetic Edits
    </div>
""", unsafe_allow_html=True)